### ISSUE TITLE
TypeError while running basic usage.

### ISSUE THREAD

**Issue by itzbhushan** [nestauk/clio-lite#1]
I really liked your blogpost and started trying to use your package. But I get a TypeError when I call `clio_search`. Specifically, I get the following error:

```
  File "./query_elastic_search.py", line 23, in <module>
    main()
  File "./query_elastic_search.py", line 18, in main
    total, docs = clio_search(es_url, index=index, query="shotgun")
  File "/home/ubuntu/.pyenv/versions/3.7.0/lib/python3.7/site-packages/clio_lite.py", line 288, in clio_search
    **kwargs)
  File "/home/ubuntu/.pyenv/versions/3.7.0/lib/python3.7/site-packages/clio_lite.py", line 134, in more_like_this
    max_doc_freq = int(max_doc_frac*total)
TypeError: unsupported operand type(s) for *: 'float' and 'dict'
```

Can this be fixed?

**Comment by inactivist** [comment]
@itzbhushan What elasticsearch version are you using?  I'm having the same issue when running the examples against elasticsearch 7.x.

I've posted a [quick fix here](https://github.com/inactivist/clio-lite/commit/27f21c6989c3eac20d4b9e9bd4233c0c37817df7) which seems to work against 7.x, but I'm not sure if the problem is due to changes in elasticsearch 7 or if this bug affects other versions as well.

**Comment by inactivist** [comment]
I've encountered this problem as well, when running against elasticsearch 7.x.

I've posted a [quick fix here](https://github.com/inactivist/clio-lite/commit/27f21c6989c3eac20d4b9e9bd4233c0c37817df7) but I'm not sure if this is due to differences in elasticsearch versions or something else.  Further investigation required.

**Comment by itzbhushan** [comment]
Yes, I was using Elastic search 7.x.

**Comment by jaklinger** [comment]
@itzbhushan apologies, I have been on sabbatical from work for some time and then covid happened... anyway I'm back now!

`clio-lite` was prototyped using ES 6.x but I've just migrated to using 7.x. Thanks to @inactivist for spotting the breaking change between 6.x and 7.x. Implemented in https://github.com/nestauk/clio-lite/pull/2. The functionality should be ES version agnostic now.
