### ISSUE TITLE
Questions from a blind truffle pig

### ISSUE THREAD

**Issue by weisisheng** [nestauk/clio-lite#8]
Assuming one was going to use searchkit at the front-end, I assume one would:

1. set up the toy ES instance
2. run the clio-lite script
3. install the searchkit create-react-app (or should one use the aws lambda version)?
4. wire the remaining bits up

I would welcome some additional illumination. Thanks in advance!

**Comment by jaklinger** [comment]
Hi again, and apologies again for being ridiculously slow in getting back to you!

Setup instructions for the entire arXlive website can be found [here](https://github.com/nestauk/arxlive) which include instructions on setting up the react app via Zappa to AWS (serverless, and basically free on AWS Lambda).

Regarding searchkit, if you see [this portion of the arXlive github repo](https://github.com/nestauk/arxlive/blob/master/arxlive-search/src/App.js), you will find where I have slightly modified native SearchKit for my purposes - I hope that you can reverse engineer the concept - but it is very superficial since I'm not at all a front end developer!

**Comment by jaklinger** [comment]
and to answer your question more thoroughly: yes your approach is spot on!

**Comment by jaklinger** [comment]
again, please do not hesitate to re-open if the issue is not resolved
